create database T1907A_GROUP2_Kawazaki
go
use T1907A_GROUP2_Kawazaki
go

 CREATE TABLE CUSTOMER (
	ID_ORDER int NOT NULL,
	ADDRES nvarchar(255) NOT NULL,
	POSTAL_CODE nvarchar(255) NOT NULL,
	CUSTOMER_ID int NOT NULL,
	PRIMARY KEY (CUSTOMER_ID)
);
go
CREATE TABLE ORDERS (
    CUSTOMER_ID int NOT NULL,
	TIME datetime NOT NULL,
	TICKET_ID int NOT NULL,
	EMPLOYEE_ID int NOT NULL,
	TOTAL_MONEY int NOT NULL,
	AMOUNT_TICKET nvarchar(255) NOT NULL,
	ID_ORDER int NOT NULL,
	PRIMARY KEY (ID_ORDER),
);
go
CREATE TABLE ACCOUNT (
	CUSTOMER_ID int NOT NULL,
	ACCOUNT_ID int NOT NULL,
	OPEN_DATE datetime NOT NULL,
	EMPLOYEE_ID int NOT NULL,
	PRIMARY KEY (CUSTOMER_ID)
);
go
CREATE TABLE INFORMATION (
	CUSTOMER_ID int NOT NULL,
	FIRST_NAME nvarchar(255) NOT NULL,
	LAST_NAME nvarchar(255) NOT NULL,
	PHONE nvarchar(255) NOT NULL,
	AGE nvarchar(255),
	PRIMARY KEY (CUSTOMER_ID)
);
go
CREATE TABLE ZOO (
	ZOO_ID int NOT NULL,
	PRIMARY KEY (ZOO_ID)
);
go
CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID int NOT NULL,
	LAST_NAME nvarchar(255) NOT NULL,
	ADDRESS nvarchar(255) NOT NULL,
	PHONE nvarchar(255) NOT NULL,
	PART nvarchar(255) NOT NULL,
	ZOO_ID int NOT NULL,
	PRIMARY KEY (EMPLOYEE_ID)
);
go
CREATE TABLE EVENT (
	ZOO_ID int NOT NULL,
	NAME_EVENT nvarchar(255) NOT NULL,
	TIME_TO_START nvarchar(255) NOT NULL,
	ATTRACTINO_TIME nvarchar(255) NOT NULL,
	PRIMARY KEY (NAME_EVENT)
);
go
CREATE TABLE ANIMAL (
	NAME_ANIMAL nvarchar(255) NOT NULL,
	AMOUNT int,
	CLASSIFY nvarchar(255),
	ZOO_ID int NOT NULL,
	PRIMARY KEY (NAME_ANIMAL)
);
go
CREATE TABLE TICKET (
	ID_TICKET int NOT NULL,
	CLASSIFY nvarchar(255) NOT NULL,
	DURATION nvarchar(255) NOT NULL ,
	ZOO_ID int NOT NULL,
	ID_ORDER int NOT NULL,
	PRIMARY KEY (ID_TICKET)
);
go
ALTER TABLE ORDERS 
ADD CONSTRAINT CUSTOMER_ORDER_fk 
FOREIGN KEY (CUSTOMER_ID) 
REFERENCES CUSTOMER (CUSTOMER_ID);

ALTER TABLE ORDERS 
ADD CONSTRAINT EMPLOYEE_ORDER_fk 
FOREIGN KEY (EMPLOYEE_ID) 
REFERENCES EMPLOYEE (EMPLOYEE_ID);

ALTER TABLE ACCOUNT 
ADD CONSTRAINT CUSTOMER_ACCOUNT_fk 
FOREIGN KEY (CUSTOMER_ID) 
REFERENCES CUSTOMER (CUSTOMER_ID);

ALTER TABLE ACCOUNT 
ADD CONSTRAINT EMPLOYEE_ACCOUNT_fk 
FOREIGN KEY (EMPLOYEE_ID) 
REFERENCES EMPLOYEE (EMPLOYEE_ID);

ALTER TABLE INFORMATION 
ADD CONSTRAINT CUSTOMER_INFORMATION_fk 
FOREIGN KEY (CUSTOMER_ID) 
REFERENCES CUSTOMER (CUSTOMER_ID);

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT ZOO_EMPLOYEE_fk 
FOREIGN KEY (ZOO_ID) 
REFERENCES ZOO (ZOO_ID);

ALTER TABLE EVENT 
ADD CONSTRAINT ZOO_EVENT_fk 
FOREIGN KEY (ZOO_ID) 
REFERENCES ZOO (ZOO_ID);

ALTER TABLE ANIMAL 
ADD CONSTRAINT ZOO_ANIMAL_fk 
FOREIGN KEY (ZOO_ID) 
REFERENCES ZOO (ZOO_ID);

ALTER TABLE TICKET 
ADD CONSTRAINT ZOO_TICKET_fk
FOREIGN KEY (ZOO_ID) 
REFERENCES ZOO (ZOO_ID);

ALTER TABLE TICKET
ADD CONSTRAINT ORDERS_TICKET_fk 
FOREIGN KEY (ID_ORDER) 
REFERENCES ORDERS (ID_ORDER);

